#ifndef __KSU_UAPI_FEATURE
#define __KSU_UAPI_FEATURE

#define KSU_FEATURE_SU_COMPAT 0
#define KSU_FEATURE_KERNEL_UMOUNT 1
#define KSU_FEATURE_SELINUX_HIDE 2
#define KSU_FEATURE_AVC_SPOOF 3

#define KSU_FEATURE_MAX 16

#endif
