#ifndef __KSU_UAPI_FEATURE
#define __KSU_UAPI_FEATURE

#include <linux/types.h>

enum ksu_feature_id {
	KSU_FEATURE_SU_COMPAT = 0,
	KSU_FEATURE_KERNEL_UMOUNT = 1,
	KSU_FEATURE_SELINUX_HIDE = 4,
	KSU_FEATURE_AVC_SPOOF = 10003,

	KSU_FEATURE_MAX
};

#endif
